When user clickes “back button” the app exits, but expected behavior should be “user goes back to previous page”
doubledashio/aw-android pull request #6
Opened 2022-04-05 12:57 UTC by harigl

https://trello.com/c/6PTMSFFs/26-when-user-clickes-back-button-the-app-exits-but-expected-behavior-should-be-user-goes-back-to-previous-page

2022-04-05 23:51 UTC, murphyalexandre requested changes

2022-04-05 23:51 UTC, murphyalexandre commented on mobile/src/main/java/ca/uqam/espaceunaw/MainActivity.kt
> +//        val view = inflater.inflate(R.layout.test_fragment, container, false)
Remove this.

2022-04-05 23:51 UTC, murphyalexandre commented on mobile/src/main/java/ca/uqam/espaceunaw/MainActivity.kt
> +var doubleBackToExitPressedOnce = false
Is this used?

2022-04-06 05:16 UTC, harigl commented on mobile/src/main/java/ca/uqam/espaceunaw/MainActivity.kt
> +var doubleBackToExitPressedOnce = false
No, now removed that line.

2022-04-06 12:44 UTC, murphyalexandre approved these changes

2022-04-08 04:22 UTC, merged